<div class="">
	<img onclick="send_sticker('AngelEmoji');" src="/logo/api3/stickers/AngelEmoji.png?r=cache" class="skiyen-sticker-img">
	<img onclick="send_sticker('AngryEmoji');" src="/logo/api3/stickers/AngryEmoji.png?r=cache" class="skiyen-sticker-img">
	<img onclick="send_sticker('AngryFace');" src="/logo/api3/stickers/AngryFace.png?r=cache" class="skiyen-sticker-img">
	<img onclick="send_sticker('BawlingEmoji');" src="/logo/api3/stickers/BawlingEmoji.png?r=cache" class="skiyen-sticker-img">
	<img onclick="send_sticker('BreakingHeartEmoji');" src="/logo/api3/stickers/BreakingHeartEmoji.png?r=cache" class="skiyen-sticker-img">
	<img onclick="send_sticker('CheekyEmoji');" src="/logo/api3/stickers/CheekyEmoji.png?r=cache" class="skiyen-sticker-img">
	<img onclick="send_sticker('CoolEmoji');" src="/logo/api3/stickers/CoolEmoji.png?r=cache" class="skiyen-sticker-img">
	<img onclick="send_sticker('CrazyEmoji');" src="/logo/api3/stickers/CrazyEmoji.png?r=cache" class="skiyen-sticker-img">
	<img onclick="send_sticker('CringeEmoji');" src="/logo/api3/stickers/CringeEmoji.png?r=cache" class="skiyen-sticker-img">
	<img onclick="send_sticker('DevilEmoji');" src="/logo/api3/stickers/DevilEmoji.png?r=cache" class="skiyen-sticker-img">
	<img onclick="send_sticker('DissatisfiedEmoji');" src="/logo/api3/stickers/DissatisfiedEmoji.png?r=cache" class="skiyen-sticker-img">
	<img onclick="send_sticker('FaceWithStraightMouthEmoji');" src="/logo/api3/stickers/FaceWithStraightMouthEmoji.png?r=cache" class="skiyen-sticker-img">
	<img onclick="send_sticker('FlirtingEmoji');" src="/logo/api3/stickers/FlirtingEmoji.png?r=cache" class="skiyen-sticker-img">
	<img onclick="send_sticker('HappyFaceEmoji');" src="/logo/api3/stickers/HappyFaceEmoji.png?r=cache" class="skiyen-sticker-img">
	<img onclick="send_sticker('HeartEmoji');" src="/logo/api3/stickers/HeartEmoji.png?r=cache" class="skiyen-sticker-img">
	<img onclick="send_sticker('HeartEyesEmoji');" src="/logo/api3/stickers/HeartEyesEmoji.png?r=cache" class="skiyen-sticker-img">
	<img onclick="send_sticker('HeavyExclamation');" src="/logo/api3/stickers/HeavyExclamation.png?r=cache" class="skiyen-sticker-img">
	<img onclick="send_sticker('KissingEmoji');" src="/logo/api3/stickers/KissingEmoji.png?r=cache" class="skiyen-sticker-img">
	<img onclick="send_sticker('LaughingEmoji');" src="/logo/api3/stickers/LaughingEmoji.png?r=cache" class="skiyen-sticker-img">
	<img onclick="send_sticker('love');" src="/logo/api3/stickers/love.png?r=cache" class="skiyen-sticker-img">
	<img onclick="send_sticker('LoveHeart');" src="/logo/api3/stickers/LoveHeart.png?r=cache" class="skiyen-sticker-img">
	<img onclick="send_sticker('LovestruckEmoji');" src="/logo/api3/stickers/LovestruckEmoji.png?r=cache" class="skiyen-sticker-img">
	<img onclick="send_sticker('NormalSmile');" src="/logo/api3/stickers/NormalSmile.png?r=cache" class="skiyen-sticker-img">
	<img onclick="send_sticker('PainedFaceEmoji');" src="/logo/api3/stickers/PainedFaceEmoji.png?r=cache" class="skiyen-sticker-img">
	<img onclick="send_sticker('PuzzledEmoji');" src="/logo/api3/stickers/PuzzledEmoji.png?r=cache" class="skiyen-sticker-img">
	<img onclick="send_sticker('RedFaceEmoji');" src="/logo/api3/stickers/RedFaceEmoji.png?r=cache" class="skiyen-sticker-img">
	<img onclick="send_sticker('sad');" src="/logo/api3/stickers/sad.png?r=cache" class="skiyen-sticker-img">
	<img onclick="send_sticker('SadfaceEmoji');" src="/logo/api3/stickers/SadfaceEmoji.png?r=cache" class="skiyen-sticker-img">
	<img onclick="send_sticker('ScreamEmoji');" src="/logo/api3/stickers/ScreamEmoji.png?r=cache" class="skiyen-sticker-img">
	<img onclick="send_sticker('Smile');" src="/logo/api3/stickers/Smile.png?r=cache" class="skiyen-sticker-img">
	<img onclick="send_sticker('SmilingFace');" src="/logo/api3/stickers/SmilingFace.png?r=cache" class="skiyen-sticker-img">
	<img onclick="send_sticker('SparklingHeart');" src="/logo/api3/stickers/SparklingHeart.png?r=cache" class="skiyen-sticker-img">
	<img onclick="send_sticker('StarEmoji');" src="/logo/api3/stickers/StarEmoji.png?r=cache" class="skiyen-sticker-img">
	<img onclick="send_sticker('StraightFacedEmoji');" src="/logo/api3/stickers/StraightFacedEmoji.png?r=cache" class="skiyen-sticker-img">
	<img onclick="send_sticker('SurprisedEmoji');" src="/logo/api3/stickers/SurprisedEmoji.png?r=cache" class="skiyen-sticker-img">
	<img onclick="send_sticker('WinkEmoji');" src="/logo/api3/stickers/WinkEmoji.png?r=cache" class="skiyen-sticker-img">
	<img onclick="send_sticker('sadcup');" src="/logo/api3/stickers/sadcup.png?r=cache" class="skiyen-sticker-img">
</div>